# -*- coding: utf-8 -*-
"""5hafta.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nhu9tMkYIbm-D-kKp5kekbeaiwn2u9ZN
"""

import numpy as np
import matplotlib.pyplot as plt

class DifferentialRobot:

    def __init__(self, x0=0.0, y0=0.0, theta0=0.0):

        self.state = np.array([x0, y0, theta0])

    def move(self, v, omega, dt):
        """
        Robotu hareket ettirir.
        v     : doğrusal hız (m/s)
        omega : açısal hız (rad/s)
        dt    : zaman adımı (s)
        """
        x, y, theta = self.state

        self.state[0] += v * np.cos(theta) * dt   # x yönünde hareket
        self.state[1] += v * np.sin(theta) * dt   # y yönünde hareket
        self.state[2] += omega * dt                # açı değişimi
        self.state[2] = (self.state[2] + np.pi) % (2 * np.pi) - np.pi

        return self.state.copy()

class OdometrySensor:

    def __init__(self, sigma_v=0.05, sigma_omega=0.02, rng_seed=42):
        self.sigma_v     = sigma_v        # hız gürültüsü
        self.sigma_omega = sigma_omega    # dönüş gürültüsü
        self.rng         = np.random.default_rng(rng_seed)
        self.state       = np.zeros(3)   # başlangıç0, 0, 0]

    def update(self, v, omega, dt):
        v_gurultulu     = v     + self.rng.normal(0, self.sigma_v)
        omega_gurultulu = omega + self.rng.normal(0, self.sigma_omega)
        x, y, theta = self.state

        self.state[0] += v_gurultulu     * np.cos(theta) * dt
        self.state[1] += v_gurultulu     * np.sin(theta) * dt
        self.state[2] += omega_gurultulu * dt
        self.state[2] = (self.state[2] + np.pi) % (2 * np.pi) - np.pi

        return self.state.copy()

class LidarSensor:

    def __init__(self, sigma_x=0.05, sigma_y=0.05, rng_seed=7):
        self.sigma_x = sigma_x    # x ölçüm gürültüsü
        self.sigma_y = sigma_y    # y ölçüm gürültüsü
        self.R       = np.diag([sigma_x**2, sigma_y**2])  # ölçüm kovaryansı
        self.rng     = np.random.default_rng(rng_seed)

    def measure(self, true_state):
        z = np.array([
            true_state[0] + self.rng.normal(0, self.sigma_x),  # x ölçümü
            true_state[1] + self.rng.normal(0, self.sigma_y)   # y ölçümü
        ])
        return z

class EKF:

    def __init__(self, init_state, Q, R):
        self.x = init_state.copy()   # başlangıç durum tahmini
        self.P = np.eye(3) * 0.1     # başlangıç belirsizlik matrisi
        self.Q = Q                   # sistem gürültüsü kovaryansı
        self.R = R                   # ölçüm gürültüsü kovaryansı

    def predict(self, v, omega, dt):
        x, y, theta = self.x

        # Tahmin
        self.x[0] += v * np.cos(theta) * dt
        self.x[1] += v * np.sin(theta) * dt
        self.x[2] += omega * dt
        self.x[2]  = (self.x[2] + np.pi) % (2 * np.pi) - np.pi

        #Jacobian matrisi F
        F = np.array([
            [1, 0, -v * np.sin(theta) * dt],
            [0, 1,  v * np.cos(theta) * dt],
            [0, 0,  1                     ]
        ])

        #Kovaryans tahmini
        # P⁻ = F · P · Fᵀ + Q
        self.P = F @ self.P @ F.T + self.Q

    def update(self, z):
        H = np.array([
            [1, 0, 0],
            [0, 1, 0]
        ])

        # S = H · P⁻ · Hᵀ + R
        S = H @ self.P @ H.T + self.R

        # K = P⁻ · Hᵀ · S⁻¹
        K = self.P @ H.T @ np.linalg.inv(S)

        innovation = z - H @ self.x

        # x̂ = x̂⁻ + K · inovasyon
        self.x = self.x + K @ innovation

        # P = (I - K·H) · P⁻
        I      = np.eye(3)
        self.P = (I - K @ H) @ self.P

#kare yörünge
def generate_square_commands(side=10.0, v=1.0, dt=0.1):
    commands = []

    n_straight = int(side / v / dt)    # 10 / 1.0 / 0.1 = 100 adım

    t_turn  = 1.5                      # 1.5 saniyede 90 derece
    omega   = (np.pi / 2) / t_turn    # ≈ 1.047 rad/s
    n_turn  = int(t_turn / dt)         # 1.5 / 0.1 = 15 adım

    for _ in range(4):
        for _ in range(n_straight):
            commands.append((v, 0.0))
        for _ in range(n_turn):
            commands.append((0.0, omega))

    return commands

def run_simulation(dt=0.1, side=10.0):

    Q = np.diag([0.01**2, 0.01**2, 0.005**2])   # sistem gürültüsü
    R = np.diag([0.05**2, 0.05**2])              # LIDAR ölçüm gürültüsü

    robot    = DifferentialRobot()
    odom     = OdometrySensor(sigma_v=0.05, sigma_omega=0.02)
    lidar    = LidarSensor(sigma_x=0.05, sigma_y=0.05)
    ekf      = EKF(init_state=np.zeros(3), Q=Q, R=R)
    commands = generate_square_commands(side=side, v=1.0, dt=dt)

    true_traj = [np.zeros(3)]    # gerçek yörünge
    odom_traj = [np.zeros(3)]    # odometri tahmini
    ekf_traj  = [np.zeros(3)]    # EKF tahmini
    times     = [0.0]            # zaman

    for i, (v, omega) in enumerate(commands):
        t = (i + 1) * dt

        true_state = robot.move(v, omega, dt)

        odom_state = odom.update(v, omega, dt)

        ekf.predict(v, omega, dt)

        if i % 5 == 0:
            z = lidar.measure(true_state)
            ekf.update(z)

        true_traj.append(true_state.copy())
        odom_traj.append(odom_state.copy())
        ekf_traj.append(ekf.x.copy())
        times.append(t)

    return (np.array(true_traj),
            np.array(odom_traj),
            np.array(ekf_traj),
            np.array(times))

def plot_results(true_traj, odom_traj, ekf_traj, times):

    #Hata
    err_odom = np.linalg.norm(true_traj[:, :2] - odom_traj[:, :2], axis=1)
    err_ekf  = np.linalg.norm(true_traj[:, :2] - ekf_traj[:, :2],  axis=1)

    #RMSE
    rmse_odom = np.sqrt(np.mean(err_odom**2))
    rmse_ekf  = np.sqrt(np.mean(err_ekf**2))
    #Yörünge
    fig,ax = plt.subplots(figsize=(8, 8))

    ax.plot(true_traj[:, 0], true_traj[:, 1],
            color='blue', lw=2.5, label='Gerçek Yörünge')
    ax.plot(odom_traj[:, 0], odom_traj[:, 1],
            color='red', lw=1.5, linestyle='--',
            label=f'Odometri (RMSE={rmse_odom:.3f} m)')
    ax.plot(ekf_traj[:, 0], ekf_traj[:, 1],
            color='green', lw=1.8, linestyle='-.',
            label=f'EKF Füzyonu (RMSE={rmse_ekf:.3f} m)')
    ax.scatter([0], [0], color='black', s=100, zorder=5, marker='*')
    ax.annotate('Başlangıç', (0, 0), xytext=(0.3, 0.4), fontsize=9)
    ax.set_xlabel('x (m)')
    ax.set_ylabel('y (m)')
    ax.set_title('Yörünge Karşılaştırması')
    ax.legend()
    ax.set_aspect('equal')
    ax.grid(True, alpha=0.3)
    fig.tight_layout()
    print("\n" * 3)

    #Konum hatası-zaman
    fig2,ax = plt.subplots(figsize=(8, 8))
    ax.plot(times, err_odom, color='red', lw=1.4,
            label=f'Odometri  RMSE = {rmse_odom:.3f} m')
    ax.fill_between(times, err_odom, alpha=0.15, color='red')
    ax.plot(times, err_ekf, color='green', lw=1.6,
            label=f'EKF Füzyon RMSE = {rmse_ekf:.3f} m')
    ax.fill_between(times, err_ekf, alpha=0.15, color='green')
    ax.set_xlabel('Zaman (s)')
    ax.set_ylabel('Konum Hatası (m)')
    ax.set_title('Lokalizasyon Hatası — Zaman')
    ax.legend()
    ax.set_ylim(bottom=0)
    ax.grid(True, alpha=0.3)

    fig2.tight_layout()
    #plt.tight_layout()
    plt.savefig('simulasyon.png', dpi=150, bbox_inches='tight')
    plt.show()

    print(f"  Odometri RMSE  : {rmse_odom:.4f} m")
    print(f"  EKF RMSE       : {rmse_ekf:.4f} m")
    print(f"  İyileşme Oranı : %{(1 - rmse_ekf/rmse_odom)*100:.1f}")

if __name__ == "__main__":
    true_traj, odom_traj, ekf_traj, times = run_simulation(dt=0.1, side=10.0)
    plot_results(true_traj, odom_traj, ekf_traj, times)